# Generated by Django 3.2.4 on 2021-08-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyplanner', '0002_song_is_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.FileField(upload_to=''),
        ),
    ]
